barbie/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap


urlpatterns = [

    url(r'^', include('mainapp.urls')),
    url(r'^', include('campamentopop.urls')),
    url(r'^', include('perritos.urls')),
    url(r'^', include('superprincesas.urls')),
    url(r'^', include('fashion.urls')),
    url(r'^google3916edec6e930323.html', TemplateView.as_view(template_name='google/google.html')),
    #url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.conf import settings
from django.conf.urls import *

urlpatterns = patterns('mainapp.views',
    # Examples:
    url(r'^$', 'home', name='home'),
    url(r'^sitemap.xml', 'sitemap', name='sitemap'),
    url(r'^pais', 'paises', name='paises'),
    
    url(r'^logueate', 'logueate', name='logueate'),
    url(r'^login', 'login_view', name='login_view'),
    url(r'^registrate', 'registrate', name='registrate'),
    url(r'^activa', 'activa', name='activa'),
    url(r'^conmispapas', 'parentform', name='parentform'),
    url(r'^sola', 'aloneform', name='aloneform'),
    url(r'^form/parent', 'parentform', name='parentform'),
    url(r'^reg/alone', 'reg_alone', name='reg_alone'),
    url(r'^reg/activate', 'parentactv', name='parentactv'),
    url(r'^reg/parent', 'parent_reg', name='parent_reg'),
    url(r'^reg/renueva_reg', 'renueva_reg', name='renueva_reg'),
    url(r'^renueva', 'renueva', name='renueva'),
    url(r'^salir/', 'salir', name='salir'),
    url(r'^perfil/', 'perfil', name='perfil'),
    url(r'^cities', 'cities', name='cities'),
    url(r'^mailing', 'mailing', name='mailing'),
    
    #url(r'^form/', 'form', name='form'),
    #url(r'^setstatus/(?P<iddv>\d+)/$', 'setstatus', name='setstatus'),
    #url(r'^interfaz_form/(?P<iddv>\d+)/', 'interfaz_form', name='interfaz_form'),
    #url(r'^adding/', 'adding', name='adding'),
    #rl(r'^addinterfaz/', 'addinterfaz', name='addinterfaz'),
    #url(r'^device/(?P<iddv>\d+)/$', 'device', name='device'),
    #url(r'^device_form/(?P<iddv>\d+)/$', 'device_form', name='device_form'),
    #url(r'^deviceslist/', 'deviceslist', name='deviceslist'),
    #url(r'^logoff/', 'logoff', name='logoff'),

)

mainapp/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User


GENRERS = ((u'Niño',u'Niño'),(u'Niña',u'Niña'))


class Country(models.Model):

	contry_name = models.CharField(u'Nombre',max_length=200)
	subfix = models.CharField(u'Subfijo',max_length=5)
	active = models.BooleanField(default=False)
	order = models.IntegerField(u'orden',blank=True,null=True,default=0)
	def __unicode__(self):
		return u'%s'%(self.contry_name)


class City(models.Model):
	country_id = models.ForeignKey(Country)
	city_name = models.CharField(u'Nombre',max_length=200)
	active = models.BooleanField(default=False)
	order = models.IntegerField(u'orden',blank=True,null=True,default=0)
	subfix_city = models.CharField(u'Subfijo',max_length=5,default='0')
	def __unicode__(self):
		return u'%s'%(self.city_name)



class Passimg(models.Model):
	rowup = models.ImageField(u'imagen renglon arriba',upload_to='pass')
	keyup = models.CharField(u'valor',max_length=50)
	rowdown = models.ImageField(u'Imagen abajo',upload_to='pass')
	keydown = models.CharField(u'valor',max_length=50)	


class BarbieUser(models.Model):
	sysuser = models.ForeignKey(User)
	name = models.CharField(u'Nombre de tu hija(o):',max_length=200)
	apaterno = models.CharField(u'Apellido Paterno:',max_length=200,default='')
	amaterno = models.CharField(u'Apellido Materno:',max_length=200,default='')
	adress = models.CharField(u'direccion:',max_length=200,default='')
	nickname = models.CharField(u'nickname',max_length=200,unique=True)
	enabled = models.BooleanField(u'enabled',max_length=200)
	dob	 = models.DateField(u'Fecha de Cumpleaños',max_length=200,blank=True,null=True)
	gender = models.CharField(u'Genero',max_length=10,choices = GENRERS,blank=True,null=True)
	password = models.CharField(u'Contraseña',max_length=200)
	sign_count = models.IntegerField('contadorLogin',default=1)
	sign_date = models.DateTimeField('agregado',auto_now_add=True)
	confirmation_token = models.BooleanField('confirmacion enviada',default=0)
	fecha_confirmacion = models.DateTimeField('confirmado en',blank=True,null=True)
	country = models.ForeignKey(Country)
	province = models.CharField(u'Provincia',max_length=200,default='')
	status = models.BooleanField('estatus',default=0)
	sign_ip = models.CharField('IP_logueo_actual',max_length=50)
	register_ip = models.CharField('IP_registro',max_length=50)
	ip_last_sign = models.CharField('ultima_ip',max_length=50)
	email = models.EmailField(u'Tu correo electrónico',max_length=200,default='',blank=True,null=True)
	current_login_at = models.DateTimeField('current login',blank=True,null=True)
	last_login_at = models.DateTimeField('last login',blank=True,null=True)
	total_score = models.IntegerField('score',default=0,blank=True,null=True)


	def __unicode__(self):
		return '%s %s'%(self.nickname,self.country)


class ParentUser(models.Model):
	sonsuser = models.ManyToManyField(BarbieUser)
	name = models.CharField(u'Nombre',max_length=200,default='')
	parent_accept = models.BooleanField(u'acepta terminos')
	newsletter_accept = models.BooleanField(u'Desea recibir correos',default=False)
	email_parent = models.EmailField(u'Tu correo electrónico',max_length=200)
	phone = models.CharField(u'Telefono',max_length=50,default='')



class Scoreuser(models.Model):
	usuariobarbie = models.ForeignKey(BarbieUser,related_name='scoreusuario',blank=True,null=True)
	description = models.TextField(blank=True,null=True)
	score = models.IntegerField(blank=True,null=True,default=0)
	created_at = models.DateTimeField(auto_now_add=True)
	campain = models.CharField(max_length=200,blank=True,null=True)


	def __unicode__(self):
		return self.email_parent

mainapp/views.py
# -*- encoding: utf-8 -*-
from django.http import HttpResponse
from django.template.context import RequestContext
from django.shortcuts import  render_to_response,render
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import redirect
import string as STrg
import datetime
from mainapp.models import *
import simplejson
from django.db.models import  get_app,get_models
from django.forms.models import model_to_dict
from django.contrib import auth
from django.core.mail import send_mail
from barbie.forms import * 
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.contrib.auth.hashers import make_password
from geoip import geolite2
from django.utils import timezone
import pytz
from django.utils.timezone import activate
import csv
import bz2 
import re

FLAGS = {'ar':'flagLatam.png','mx':'flagMx.png','col':'flagCol.png','pe':'flagPe.png','chi':'flagChi.png','latam':'flagLatam.png'}


def mailing(request):
    context = RequestContext(request)
    keyus = request.POST.get('keyus',None)

    if request.COOKIES.has_key( keyus ):
        #value = request.COOKIES[ 'cookie_name' ]
        return HttpResponse('ya se envio')
    else:
        if keyus:
            buser = BarbieUser.objects.get(pk=keyus)
            try:
                mail_to = buser.sysuser.email
            except:
                mail_to = buser.email


            link = 'http://%s/activa?block=%s'%('vivebarbie.com',buser.pk)
            email_body = render_to_string("mailing/registro_sola.html", {'host':'vivebarbie.com','nickname':buser.nickname,'link': link})
            send_mail('Informacion de padres','','Vive Barbie <registro@vivebarbie.com>',[mail_to], fail_silently=False,html_message=email_body)
            response = HttpResponse( 'enviado' )
            max_age = 1 * 24 * 60 * 60
            response.set_cookie( keyus, 'ya se envio' ,max_age=max_age)
            return response
        else:
            assert False,'algo no esta bien'


# VIEWS'S SITE HERE -------------------------------------------------------------------------

def get_country(request):
    ip_user = request.environ.get('HTTP_X_REAL_IP')
    match = geolite2.lookup(ip_user)
    return match.country.lower()

def country_by_url(request):
    hostname = request.environ.get('HTTP_HOST').replace('www.','')
    hpices = hostname.split('.')
    country = Country.objects.all().values('subfix')
    cty = ['%s'%x.values()[0] for x in country]
    if hpices[0] in cty:
        mycountry=hpices[0]
    else:
        mycountry='latam'
    return mycountry

def get_ip(request):
    ip_user = request.environ.get('HTTP_X_REAL_IP')
    return ip_user

def get_title(request,title,principal=' ',onlyhome=''):
    cbyurl = country_by_url(request)
    try:
        pais_name = Country.objects.get(subfix=cbyurl)
    except:
        pais_name = 'LATAM'

    cadena = '%sBarbie%s %s | %s'%(onlyhome,principal,pais_name,title)

    return cadena

def sitemap(request):
    country = country_by_url(request)
    context = RequestContext(request)
    template = 'sitemaps/%s/sitemap.xml'%(country)
    response = render_to_response(template,{},context)
    response['Content-Type'] = 'text/xml; charset=utf-8'
    return response


def home(request):
    args = {}
    context = RequestContext(request)
    country = Country.objects.all().values('subfix')    
    cty = [(str(x['subfix'].lower()),) for x in country]
    getcountry = get_country(request)
    if getcountry in cty[0]:
        mycountry=getcountry
    else:
        mycountry='latam'

    if mycountry=='latam':
        sublink = '/pais'
    else: 
        sublink = ''
    hostname = request.environ.get('HTTP_HOST').replace('www.','')
    hpices = hostname.split('.')
    newlink = 'http://%s.%s'%(mycountry,hostname)

    args['myip']=request.environ.get('HTTP_HOST')
    
    cbyurl = country_by_url(request)
    try:
        pais_name = Country.objects.get(subfix=cbyurl)
    except:
        pais_name = 'LATAM'
    args['titulo']=get_title(request,'Barbie',principal='.com',onlyhome='Vive')

    if hostname=='vivebarbie.com':
        if len(hpices)<3:
            newlink = 'http://%s.vivebarbie.com%s'%(mycountry,sublink)
            return redirect(newlink)
        else:
            request.mycountryflag = FLAGS[country_by_url(request)]
            return render_to_response("home.html",args,context)


    if len(hpices)<4 and hostname=='devel.vivebarbie.com':
        newlink = 'http://%s.devel.vivebarbie.com%s'%(mycountry,sublink)
        return redirect(newlink)
    else:
        request.mycountryflag = FLAGS[country_by_url(request)]
        return render_to_response("home.html",args,context)



def paises(request):
    #ip_user = request.environ.get('HTTP_X_REAL_IP')
    #match = geolite2.lookup(ip_user)
    #tz = match.timezone
    #activate(tz)
    #assert False,timezone.now()
    mycountry = country_by_url(request)
    request.mycountryflag = FLAGS[mycountry]

    args = {}
    args['titulo']='cambio de pais'
    context = RequestContext(request)
    country = Country.objects.all().values('subfix')
    cty = [(str(x['subfix'].lower()),) for x in country]
    getcountry = get_country(request)
    if getcountry in cty[0]:
        mycountry=getcountry
    else:
        mycountry='latam'
    hostname = request.environ.get('HTTP_HOST').replace('www.','')
    hpices = hostname.split('.')
    newlink = 'http://%s.%s'%(mycountry,hostname)
    args['myip']=request.environ.get('HTTP_HOST')

    args['titulo']=get_title(request,'Elije tu país')
    

    '''
    if hostname=='vivebarbie.com':
        if len(hpices)<3:
            newlink = 'http://%s.vivebarbie.com'%mycountry
            return redirect(newlink)
        else:

            return render_to_response("inicio.html",args,context)


    if len(hpices)<4 and hostname=='devel.vivebarbie.com':
        return redirect(newlink)
    else:
    '''
    return render_to_response("inicio.html",args,context)


def logueate(request):
    args = {}
    context = RequestContext(request)
    return render_to_response("forms/login.html",args,context)

def registrate(request):
    args = {}
    context = RequestContext(request)
    args['titulo']='registrate'
    args['titulo']=get_title(request,'Registrate')
    return render_to_response("registro.html",args,context)

'''

    @ Building a Form for kids in alone_mode

'''

def aloneform(request):

    args = {}
    context = RequestContext(request)

    form = FormCreator()
    fields = ['nickname','password','email','name','apaterno','amaterno']
    widgets = {
            'password':forms.HiddenInput(attrs={}),
            'email':forms.TextInput(attrs={}),
            
    }
    
    userform = form.advanced_form_to_model(BarbieUser,fields=fields,widgets=widgets)
    #passcombo = Passimg.objects.all()
    args['uform'] = userform
    #args['passcombo'] = passcombo
    args['titulo']=get_title(request,'Registrate sola')
    return render_to_response("forms/regalone.html",args,context)

'''
    @Saving the kid info in alone_mode

'''

def reg_alone(request):
    data = request.POST.copy()
    correo = request.POST.get('email',None)
    doll = request.POST.get('doll',None)
    figure = request.POST.get('figure',None)

    response = {}
    excludes = {}
    form = FormCreator()
    forma = form.advanced_form_to_model(BarbieUser,excludes=excludes)
    country = get_country(request)
    ip = get_ip(request)
    usernamer = data['nickname']
    countryreg = Country.objects.filter(subfix=country)
    try: 
        usercheck = User.objects.get(nickname=data['nickname'])
    except:
        usercheck =  None


    utemp = User.objects.get(username='saruman')
    extradata = {'ip_last_sign':ip,'country':countryreg,'sign_ip':ip,'sign_count':1,'confirmation_token':1,
                 'register_ip':ip,'sysuser':utemp.pk,'province':' ','adress':' '
                }

    data.update(extradata)

    forma = forma(data)

    if usercheck:
        forma.errors.update({'nickname':'el usuario ya existe'})

    if not correo:
        forma.errors.update({'email':'Este campo es obligatorio.'})        

    if not doll or not figure:
        forma.errors.update({'password':'Tu contraseña esta incompleta.'})        

    if forma.is_valid():
        saved = forma.save()
        usersys,fail = User.objects.get_or_create(username=usernamer,password=make_password(data['password']),email=data['email'])
        usersys.is_staff=True
        usersys.is_active = True
        usersys.save()
        saved.sysuser = usersys
        saved.last_login_at = saved.current_login_at
        saved.current_login_at = timezone.now()
        saved.email=''
        saved.password = make_password(data['password'])
        saved.save()
        keycompres = '%s'%saved.pk
        #keycompres = bz2.compress(keycompres)
        hostname = request.environ.get('HTTP_HOST').replace('www.','')
        link = 'http://%s/activa?block=%s'%(hostname,keycompres)
        email_body = render_to_string("mailing/registro_sola.html", {'host':hostname,'nickname': data['nickname'],'link': link,'pass':(doll,figure)})
        send_mail('Informacion de padres','','Vive Barbie <registro@vivebarbie.com>',[data['email']], fail_silently=False,html_message=email_body)
        usernew = auth.authenticate(username = usernamer, password = data['password'])
        auth.login(request,usernew)
        response['saved']='ok'
        response['callback']='saved_alone'
        
    else:
        response['err']='ok'
        response['data']=forma.errors
    return HttpResponse(simplejson.dumps(response))

def parentform(request):
    args = {}
    context = RequestContext(request)
    nickname = request.GET.get('block',None)
    if nickname:
        instance = BarbieUser.objects.get(pk=nickname)
        initial = instance.email
    else:
        instance = None
        initial = None
    form = FormCreator()

mainapp/templates/forms/parentactivate.html
{% extends 'base2.html' %}

{% block content %}

    <div class="container legalContainer" style="min-height:650px;">
        <div class="row">
            <div class="col-md-12 col-sm-12 content-holder text-center">
              <div class="bienvenida img-responsive terms container-fluid">REGISTRO</div>
              
              <div class="container-fluid">
                <div class="row">
                  <div class="col-md-1 col-sm-1"></div>
                  <div class="col-md-10 col-sm-10">
                  {% if instance.enabled %}
      
                      <p>Tu cuenta ya esta activada, gracias. :)</p>
                  {% else %}
           
            <form name="regparent" id="activate_form" method="post" action="/reg/activate"  class="sender registroBarbie" >
                <input type="hidden" name="pk" value="{{instance.pk}}"/>
              <!--  FORMULARIO -->
                <div class="col-md-12">
                  <div class="col-md-4 regLabelBox"><i class="fa fa-play"></i>
                    <label>Nickname *:</label>
                  </div>
                  <div class="col-md-8">
                    {{uform.nickname}}
                  </div>
                </div>


                <div class="col-md-12">
                  <div class="col-md-4 regLabelBox"><i class="fa fa-play"></i>
                    <label>Nombre*:</label>
                  </div>
                  <div class="col-md-8">
                    {{uform.name}}
                  </div>
                </div>

                <div class="col-md-12">
                  <div class="col-md-4 regLabelBox"><i class="fa fa-play"></i>
                    <label>Apellido Paterno*:</label>
                  </div>
                  <div class="col-md-8">
                    {{uform.apaterno}}
                  </div>
                </div>


                <div class="col-md-12">
                  <div class="col-md-4 regLabelBox"><i class="fa fa-play"></i>
                    <label>Apellido Materno *:</label>
                  </div>
                  <div class="col-md-8">
                    {{uform.amaterno}}
                  </div>
                </div>                



                <div class="col-md-12">
                  <div class="col-md-4 regLabelBox"><i class="fa fa-play"></i>
                    <label>Cumpleaños:</label>
                  </div>
                  <div class="col-md-8" id="id_dob">
                    <select name="dia">
                      <option value="">Día</option>
                      {% for i in dias %}
                      <option value="{{i}}">{{i}}</option>
                      {% endfor %}
                    </select>
                    <select name="mes">
                      
                      {% for m in nmeses %}
                      <option value="{{ forloop.counter0 }}">{{m}}</option>
                      {% endfor %}
                    </select>
                    <select name="anyo">
                      <option value="">Año</option>
                      {% for a in anyos %}
                      <option value="{{a}}">{{a}}</option>
                      {% endfor %}
                    </select>

                  </div>
                </div>
                <div class="col-md-12">
                  <div class="col-md-4 regLabelBox"><i class="fa fa-play"></i>
                    <label>eMail de tus papás *:</label>
                  </div>
                  <div class="col-md-8">
                    {{pform.email_parent}}
                  </div>
                </div>


                <div class="col-md-12">
                  <div class="col-md-4 regLabelBox"><i class="fa fa-play"></i>
                    <label>Teléfono papás*:</label>
                  </div>
                  <div class="col-md-8">
                    {{pform.phone}}
                  </div>
                </div>

                <div class="col-md-12">
                  <div class="col-md-4 regLabelBox"><i class="fa fa-play"></i>
                    <label id="id_gender">Género *:</label>
                  </div>
                  <div class="col-md-8">
                    <div class="radioCont">
                      <input type="radio" id="radio01" name="gender" value="Niña" />
                      <label for="radio01"><span></span>Niña</label>
                    </div>

                    <div class="radioCont">
                     <input type="radio" id="radio02" name="gender" value="Niño" />
                     <label for="radio02"><span></span>Niño</label>
                    </div>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="col-md-4 regLabelBox"><i class="fa fa-play"></i>
                    <label>País *:</label>
                  </div>
                  <div class="col-md-8">
                     {{uform.country}}
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="col-md-4 regLabelBox"><i class="fa fa-play"></i>
                    <label>Estado/Provincia *:</label>
                  </div>
                  <div class="col-md-8">
                      <select name="province" id="id_province" class="registroSelect">
                        <option value="">seleccione...</option>
                      {% for c in instance.country.city_set.all %}
                        <option value="{{c}}">{{c}}</option>
                      {% endfor %}
                    </select>
                    
                  </div>
                </div>



                <div class="col-md-12">
                  <div class="col-md-4 regLabelBox"><i class="fa fa-play"></i>
                    <label>Dirección*:</label>
                  </div>
                  <div class="col-md-8">
                    {{uform.adress}}
                  </div>
                </div>                

                <div class="col-md-12">
                  <div class="col-md-6 regLabelBox" ><i class="fa fa-play"></i>
                    <label id="id_newsletter_accept">¿Quieres recibir noticias? *:</label>
                  </div>
                  <div class="col-md-6">
                    <div class="radioCont">
                      <input type="radio" id="id_newsletter_accept1" name="newsletter_accept" value="1" />
                      <label for="id_newsletter_accept1"><span></span>Si</label>
                    </div>

                    <div class="radioCont">
                      <input type="radio" id="id_newsletter_accept2" name="newsletter_accept" value="0"  />
                     <label for="id_newsletter_accept2"><span></span>No</label>
                    </div>
                  </div>
                </div>
                <div class="col-md-12" >
                  <div class="col-md-6 regLabelBox"><i class="fa fa-play"></i>
                    <label id="id_parent_accept">Acepto las <a href="/static/politicas-de-privacidad.html" target="_blank">políticas de privacidad</a> *:</label>
                  </div>
                  <div class="col-md-6">
                    <div class="radioCont izqForm">
                      <input type="checkbox" id="terminos01" name="parent_accept" value="1" />
                      <label for="terminos01"><span></span>Si</label>
                    </div>


                  </div>
                </div>

                <!--  FORMULARIO -->
                {%csrf_token%}
            
                <input type="submit" value="ACTIVAR CUENTA" />
                <br/><br/><br/>
                <div class="formLegal">
                  Nota: Los campos marcados con * son obligatorios.
                  <br>
                  *En caso de ser ganador de alguna promoción de Barbie, se te estará contactando a la información que proporciones en este registro
                </div>
            </form>


                  {% endif %}

                  </div>
                </div>
              </div>
              
            </div>
          </div>
    </div>


 <script type="text/javascript" src="/static/js/passwords.js"></script>
 <script type="text/javascript">

$(document).ready(function(){

  $('[name=dia]').val('{{instance.dob.day}}');
  $('[name=mes]').val('{{instance.dob.month}}');
  $('[name=anyo]').val('{{instance.dob.year}}');
  $('#id_phone').val('{{instance.parentuser_set.all.0.phone}}');
  if('{{instance.gender}}'=='Niño'){
    $('#radio02').attr('checked','checked');
  }
  if('{{instance.gender}}'=='Niña'){
    $('#radio01').attr('checked','checked');
  }


  if('{{instance.parentuser_set.all.0.parent_accept}}'=='True'){
    $('#terminos01').attr('checked','checked');

  }


  if('{{instance.parentuser_set.all.0.newsletter_accept}}'=='True'){
    $('#id_newsletter_accept1').attr('checked','checked');
  }



  $('#id_country').change();
  $('#id_province').val('{{instance.province}}');

});






 </script>
{% endblock %}