barbie/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap


urlpatterns = [

    url(r'^', include('mainapp.urls')),
    url(r'^', include('campamentopop.urls')),
    url(r'^', include('perritos.urls')),
    url(r'^', include('superprincesas.urls')),
    url(r'^', include('fashion.urls')),
    url(r'^google3916edec6e930323.html', TemplateView.as_view(template_name='google/google.html')),
    #url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.conf import settings
from django.conf.urls import *

urlpatterns = patterns('mainapp.views',
    # Examples:
    url(r'^$', 'home', name='home'),
    url(r'^sitemap.xml', 'sitemap', name='sitemap'),
    url(r'^pais', 'paises', name='paises'),
    
    url(r'^logueate', 'logueate', name='logueate'),
    url(r'^login', 'login_view', name='login_view'),
    url(r'^registrate', 'registrate', name='registrate'),
    url(r'^activa', 'activa', name='activa'),
    url(r'^conmispapas', 'parentform', name='parentform'),
    url(r'^sola', 'aloneform', name='aloneform'),
    url(r'^form/parent', 'parentform', name='parentform'),
    url(r'^reg/alone', 'reg_alone', name='reg_alone'),
    url(r'^reg/activate', 'parentactv', name='parentactv'),
    url(r'^reg/parent', 'parent_reg', name='parent_reg'),
    url(r'^reg/renueva_reg', 'renueva_reg', name='renueva_reg'),
    url(r'^renueva', 'renueva', name='renueva'),
    url(r'^salir/', 'salir', name='salir'),
    url(r'^perfil/', 'perfil', name='perfil'),
    url(r'^cities', 'cities', name='cities'),
    url(r'^mailing', 'mailing', name='mailing'),
    
    #url(r'^form/', 'form', name='form'),
    #url(r'^setstatus/(?P<iddv>\d+)/$', 'setstatus', name='setstatus'),
    #url(r'^interfaz_form/(?P<iddv>\d+)/', 'interfaz_form', name='interfaz_form'),
    #url(r'^adding/', 'adding', name='adding'),
    #rl(r'^addinterfaz/', 'addinterfaz', name='addinterfaz'),
    #url(r'^device/(?P<iddv>\d+)/$', 'device', name='device'),
    #url(r'^device_form/(?P<iddv>\d+)/$', 'device_form', name='device_form'),
    #url(r'^deviceslist/', 'deviceslist', name='deviceslist'),
    #url(r'^logoff/', 'logoff', name='logoff'),

)

mainapp/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User


GENRERS = ((u'Niño',u'Niño'),(u'Niña',u'Niña'))


class Country(models.Model):

	contry_name = models.CharField(u'Nombre',max_length=200)
	subfix = models.CharField(u'Subfijo',max_length=5)
	active = models.BooleanField(default=False)
	order = models.IntegerField(u'orden',blank=True,null=True,default=0)
	def __unicode__(self):
		return u'%s'%(self.contry_name)


class City(models.Model):
	country_id = models.ForeignKey(Country)
	city_name = models.CharField(u'Nombre',max_length=200)
	active = models.BooleanField(default=False)
	order = models.IntegerField(u'orden',blank=True,null=True,default=0)
	subfix_city = models.CharField(u'Subfijo',max_length=5,default='0')
	def __unicode__(self):
		return u'%s'%(self.city_name)



class Passimg(models.Model):
	rowup = models.ImageField(u'imagen renglon arriba',upload_to='pass')
	keyup = models.CharField(u'valor',max_length=50)
	rowdown = models.ImageField(u'Imagen abajo',upload_to='pass')
	keydown = models.CharField(u'valor',max_length=50)	


class BarbieUser(models.Model):
	sysuser = models.ForeignKey(User)
	name = models.CharField(u'Nombre de tu hija(o):',max_length=200)
	apaterno = models.CharField(u'Apellido Paterno:',max_length=200,default='')
	amaterno = models.CharField(u'Apellido Materno:',max_length=200,default='')
	adress = models.CharField(u'direccion:',max_length=200,default='')
	nickname = models.CharField(u'nickname',max_length=200,unique=True)
	enabled = models.BooleanField(u'enabled',max_length=200)
	dob	 = models.DateField(u'Fecha de Cumpleaños',max_length=200,blank=True,null=True)
	gender = models.CharField(u'Genero',max_length=10,choices = GENRERS,blank=True,null=True)
	password = models.CharField(u'Contraseña',max_length=200)
	sign_count = models.IntegerField('contadorLogin',default=1)
	sign_date = models.DateTimeField('agregado',auto_now_add=True)
	confirmation_token = models.BooleanField('confirmacion enviada',default=0)
	fecha_confirmacion = models.DateTimeField('confirmado en',blank=True,null=True)
	country = models.ForeignKey(Country)
	province = models.CharField(u'Provincia',max_length=200,default='')
	status = models.BooleanField('estatus',default=0)
	sign_ip = models.CharField('IP_logueo_actual',max_length=50)
	register_ip = models.CharField('IP_registro',max_length=50)
	ip_last_sign = models.CharField('ultima_ip',max_length=50)
	email = models.EmailField(u'Tu correo electrónico',max_length=200,default='',blank=True,null=True)
	current_login_at = models.DateTimeField('current login',blank=True,null=True)
	last_login_at = models.DateTimeField('last login',blank=True,null=True)
	total_score = models.IntegerField('score',default=0,blank=True,null=True)


	def __unicode__(self):
		return '%s %s'%(self.nickname,self.country)


class ParentUser(models.Model):
	sonsuser = models.ManyToManyField(BarbieUser)
	name = models.CharField(u'Nombre',max_length=200,default='')
	parent_accept = models.BooleanField(u'acepta terminos')
	newsletter_accept = models.BooleanField(u'Desea recibir correos',default=False)
	email_parent = models.EmailField(u'Tu correo electrónico',max_length=200)
	phone = models.CharField(u'Telefono',max_length=50,default='')



class Scoreuser(models.Model):
	usuariobarbie = models.ForeignKey(BarbieUser,related_name='scoreusuario',blank=True,null=True)
	description = models.TextField(blank=True,null=True)
	score = models.IntegerField(blank=True,null=True,default=0)
	created_at = models.DateTimeField(auto_now_add=True)
	campain = models.CharField(max_length=200,blank=True,null=True)


	def __unicode__(self):
		return self.email_parent

mainapp/views.py
# -*- encoding: utf-8 -*-
from django.http import HttpResponse
from django.template.context import RequestContext
from django.shortcuts import  render_to_response,render
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import redirect
import string as STrg
import datetime
from mainapp.models import *
import simplejson
from django.db.models import  get_app,get_models
from django.forms.models import model_to_dict
from django.contrib import auth
from django.core.mail import send_mail
from barbie.forms import * 
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.contrib.auth.hashers import make_password
from geoip import geolite2
from django.utils import timezone
import pytz
from django.utils.timezone import activate
import csv
import bz2 
import re

FLAGS = {'ar':'flagLatam.png','mx':'flagMx.png','col':'flagCol.png','pe':'flagPe.png','chi':'flagChi.png','latam':'flagLatam.png'}


def mailing(request):
    context = RequestContext(request)
    keyus = request.POST.get('keyus',None)

    if request.COOKIES.has_key( keyus ):
        #value = request.COOKIES[ 'cookie_name' ]
        return HttpResponse('ya se envio')
    else:
        if keyus:
            buser = BarbieUser.objects.get(pk=keyus)
            try:
                mail_to = buser.sysuser.email
            except:
                mail_to = buser.email


            link = 'http://%s/activa?block=%s'%('vivebarbie.com',buser.pk)
            email_body = render_to_string("mailing/registro_sola.html", {'host':'vivebarbie.com','nickname':buser.nickname,'link': link})
            send_mail('Informacion de padres','','Vive Barbie <registro@vivebarbie.com>',[mail_to], fail_silently=False,html_message=email_body)
            response = HttpResponse( 'enviado' )
            max_age = 1 * 24 * 60 * 60
            response.set_cookie( keyus, 'ya se envio' ,max_age=max_age)
            return response
        else:
            assert False,'algo no esta bien'


# VIEWS'S SITE HERE -------------------------------------------------------------------------

def get_country(request):
    ip_user = request.environ.get('HTTP_X_REAL_IP')
    match = geolite2.lookup(ip_user)
    return match.country.lower()

def country_by_url(request):
    hostname = request.environ.get('HTTP_HOST').replace('www.','')
    hpices = hostname.split('.')
    country = Country.objects.all().values('subfix')
    cty = ['%s'%x.values()[0] for x in country]
    if hpices[0] in cty:
        mycountry=hpices[0]
    else:
        mycountry='latam'
    return mycountry

def get_ip(request):
    ip_user = request.environ.get('HTTP_X_REAL_IP')
    return ip_user

def get_title(request,title,principal=' ',onlyhome=''):
    cbyurl = country_by_url(request)
    try:
        pais_name = Country.objects.get(subfix=cbyurl)
    except:
        pais_name = 'LATAM'

    cadena = '%sBarbie%s %s | %s'%(onlyhome,principal,pais_name,title)

    return cadena

def sitemap(request):
    country = country_by_url(request)
    context = RequestContext(request)
    template = 'sitemaps/%s/sitemap.xml'%(country)
    response = render_to_response(template,{},context)
    response['Content-Type'] = 'text/xml; charset=utf-8'
    return response


def home(request):
    args = {}
    context = RequestContext(request)
    country = Country.objects.all().values('subfix')    
    cty = [(str(x['subfix'].lower()),) for x in country]
    getcountry = get_country(request)
    if getcountry in cty[0]:
        mycountry=getcountry
    else:
        mycountry='latam'

    if mycountry=='latam':
        sublink = '/pais'
    else: 
        sublink = ''
    hostname = request.environ.get('HTTP_HOST').replace('www.','')
    hpices = hostname.split('.')
    newlink = 'http://%s.%s'%(mycountry,hostname)

    args['myip']=request.environ.get('HTTP_HOST')
    
    cbyurl = country_by_url(request)
    try:
        pais_name = Country.objects.get(subfix=cbyurl)
    except:
        pais_name = 'LATAM'
    args['titulo']=get_title(request,'Barbie',principal='.com',onlyhome='Vive')

    if hostname=='vivebarbie.com':
        if len(hpices)<3:
            newlink = 'http://%s.vivebarbie.com%s'%(mycountry,sublink)
            return redirect(newlink)
        else:
            request.mycountryflag = FLAGS[country_by_url(request)]
            return render_to_response("home.html",args,context)


    if len(hpices)<4 and hostname=='devel.vivebarbie.com':
        newlink = 'http://%s.devel.vivebarbie.com%s'%(mycountry,sublink)
        return redirect(newlink)
    else:
        request.mycountryflag = FLAGS[country_by_url(request)]
        return render_to_response("home.html",args,context)



def paises(request):
    #ip_user = request.environ.get('HTTP_X_REAL_IP')
    #match = geolite2.lookup(ip_user)
    #tz = match.timezone
    #activate(tz)
    #assert False,timezone.now()
    mycountry = country_by_url(request)
    request.mycountryflag = FLAGS[mycountry]

    args = {}
    args['titulo']='cambio de pais'
    context = RequestContext(request)
    country = Country.objects.all().values('subfix')
    cty = [(str(x['subfix'].lower()),) for x in country]
    getcountry = get_country(request)
    if getcountry in cty[0]:
        mycountry=getcountry
    else:
        mycountry='latam'
    hostname = request.environ.get('HTTP_HOST').replace('www.','')
    hpices = hostname.split('.')
    newlink = 'http://%s.%s'%(mycountry,hostname)
    args['myip']=request.environ.get('HTTP_HOST')

    args['titulo']=get_title(request,'Elije tu país')
    

    '''
    if hostname=='vivebarbie.com':
        if len(hpices)<3:
            newlink = 'http://%s.vivebarbie.com'%mycountry
            return redirect(newlink)
        else:

            return render_to_response("inicio.html",args,context)


    if len(hpices)<4 and hostname=='devel.vivebarbie.com':
        return redirect(newlink)
    else:
    '''
    return render_to_response("inicio.html",args,context)


def logueate(request):
    args = {}
    context = RequestContext(request)
    return render_to_response("forms/login.html",args,context)

def registrate(request):
    args = {}
    context = RequestContext(request)
    args['titulo']='registrate'
    args['titulo']=get_title(request,'Registrate')
    return render_to_response("registro.html",args,context)

'''

    @ Building a Form for kids in alone_mode

'''

def aloneform(request):

    args = {}
    context = RequestContext(request)

    form = FormCreator()
    fields = ['nickname','password','email','name','apaterno','amaterno']
    widgets = {
            'password':forms.HiddenInput(attrs={}),
            'email':forms.TextInput(attrs={}),
            
    }
    
    userform = form.advanced_form_to_model(BarbieUser,fields=fields,widgets=widgets)
    #passcombo = Passimg.objects.all()
    args['uform'] = userform
    #args['passcombo'] = passcombo
    args['titulo']=get_title(request,'Registrate sola')
    return render_to_response("forms/regalone.html",args,context)

'''
    @Saving the kid info in alone_mode

'''

def reg_alone(request):
    data = request.POST.copy()
    correo = request.POST.get('email',None)
    doll = request.POST.get('doll',None)
    figure = request.POST.get('figure',None)

    response = {}
    excludes = {}
    form = FormCreator()
    forma = form.advanced_form_to_model(BarbieUser,excludes=excludes)
    country = get_country(request)
    ip = get_ip(request)
    usernamer = data['nickname']
    countryreg = Country.objects.filter(subfix=country)
    try: 
        usercheck = User.objects.get(nickname=data['nickname'])
    except:
        usercheck =  None


    utemp = User.objects.get(username='saruman')
    extradata = {'ip_last_sign':ip,'country':countryreg,'sign_ip':ip,'sign_count':1,'confirmation_token':1,
                 'register_ip':ip,'sysuser':utemp.pk,'province':' ','adress':' '
                }

    data.update(extradata)

    forma = forma(data)

    if usercheck:
        forma.errors.update({'nickname':'el usuario ya existe'})

    if not correo:
        forma.errors.update({'email':'Este campo es obligatorio.'})        

    if not doll or not figure:
        forma.errors.update({'password':'Tu contraseña esta incompleta.'})        

    if forma.is_valid():
        saved = forma.save()
        usersys,fail = User.objects.get_or_create(username=usernamer,password=make_password(data['password']),email=data['email'])
        usersys.is_staff=True
        usersys.is_active = True
        usersys.save()
        saved.sysuser = usersys
        saved.last_login_at = saved.current_login_at
        saved.current_login_at = timezone.now()
        saved.email=''
        saved.password = make_password(data['password'])
        saved.save()
        keycompres = '%s'%saved.pk
        #keycompres = bz2.compress(keycompres)
        hostname = request.environ.get('HTTP_HOST').replace('www.','')
        link = 'http://%s/activa?block=%s'%(hostname,keycompres)
        email_body = render_to_string("mailing/registro_sola.html", {'host':hostname,'nickname': data['nickname'],'link': link,'pass':(doll,figure)})
        send_mail('Informacion de padres','','Vive Barbie <registro@vivebarbie.com>',[data['email']], fail_silently=False,html_message=email_body)
        usernew = auth.authenticate(username = usernamer, password = data['password'])
        auth.login(request,usernew)
        response['saved']='ok'
        response['callback']='saved_alone'
        
    else:
        response['err']='ok'
        response['data']=forma.errors
    return HttpResponse(simplejson.dumps(response))

def parentform(request):
    args = {}
    context = RequestContext(request)
    nickname = request.GET.get('block',None)
    if nickname:
        instance = BarbieUser.objects.get(pk=nickname)
        initial = instance.email
    else:
        instance = None
        initial = None
    form = FormCreator()

mainapp/templates/main_bar copy.html
<div class="container-fluid topMenuContainer" id="topMenuID">
  <div class="row">
      <div class="topMenu" id="topMenuAbre"><img src="/static/images/topMenu.png"></div>
      <div class="topMenuLogo" id="topMenuCierra"><img src="/static/images/topMenuLogo.png"></div>
      <div class="col-md-12">

        <div class="nombre">

            {% if request.user.is_active %}
            <div>¡Hola, {{request.user.barbieuser_set.all.0.nickname}}!</div>
            <div class="puntos">Tienes <span>100</span> estrellas</div>
            <div><a href="/salir/">salir</a></div>
            {% else %}
            <a href="/registrate">Registrate</a><br/>
            <a data-toggle="modal" href="#/logueate" data-target="#myModal">Inicia sesión</a>
            {% endif %}
        </div>
      </div>





<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                 <h4 class="modal-title">Inicia sesión</h4>

            </div>
            <div class="modal-body">
              <div class="te">
                <div id="login_box">
                  <form name="login_form" id="login_form" method="post" action="/login" class="sender">
                      <div id="id_nologin">{</div>
                      {%csrf_token%}
                      <div>
                          <label></label>
                          <input type="text" name="user" value="" placeholder="nickname" /> 
                      </div>
                      <div>
                          <label></label>
                          <input type="password" name="pw" value="" placeholder="xxx" /> 
                      </div>
                      <input type="submit" value="login" />
                  </form>
                </div>

              </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="goin">¡ENTRA!</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<script type="text/javascript">

$('#goin').click(function(){
  $('#login_form').submit();

});
</script>


  </div>
</div>

mainapp/templates/main_bar.html
    <!--  TweenMax Para todos las paginas TO-DAS -->
    <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/79424/TweenMax.min.js"></script>
    <!--  End TweenMax Para todos las paginas TO-DAS -->

    <div class="container-fluid topMenuContainerPurple" id="topMenuID">
      <div class="row pull-down">
        <div class="col-md-12">
            <div class="col-md-12 mobilePaddingTop"></div>
            <div class="col-md-5 listCampains">
              <ul>
                <li><a href="/"><img src="/static/vivebarbie/images/topmenu/btnHome.png"></a></li>
                <li><a href="/campamento-pop/"><img src="/static/vivebarbie/images/topmenu/btnPop.png"></a></li>
                <li><a href="/aventura-perritos/"><img src="/static/vivebarbie/images/topmenu/btnPerritos.png"></a></li>
                <li><a href="/fashion-studio/"><img src="/static/vivebarbie/images/topmenu/btnFashion.png"></a></li>
                <li><a href="/super-princesas/"><img src="/static/vivebarbie/images/topmenu/btnSuper.png"></a></li>
              </ul>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-5 infoUser listCampains">  
                <div class="col-md-5">
                  <ul>
                    <li><a href="http://kids.barbie.com/es-lam/promo/dreamtopia" target="_blank"><img src="/static/vivebarbie/images/topmenu/btnReinos.png"></a></li>
                    <li><a href="http://kids.barbie.com/es-lam/game/spy-squad-academy" target="_blank"><img src="/static/vivebarbie/images/topmenu/btnEscuadron.png"></a></li>
                  </ul>     
                </div>   
                {% if request.user.is_active %}
                <div class="col-md-7">
                  <div class="topBtnLogin">
                      <div class="nombreReg">¡Hola, {{request.user.barbieuser_set.all.0.nickname}}!</div>
                      <div class="puntos" style="display:none;">Tienes <span>100</span> estrellas</div>
                      <a href="/perfil/"><div class="iconLogTop"><i class="fa fa-user"></i> Perfil</div></a>
                      <a href="/salir/"><div class="iconLogTop"><i class="fa fa-sign-out"></i>Salir</div></a>
                  </div>
                </div>
                {% else %}
                <div class="col-md-7">
                  <script>
                    $(document).ready(function(){
                        $('[data-toggle="tooltip"]').tooltip(); 
                    });
                  </script>
                  <style type="text/css">
                  .Stooltip > .tooltip-inner {
                      background-color: #ffee07; 
                      color: #d84089; 
                      padding: 10px;
                      font-size: 15px;
                  }

                  </style>
                  <div class="topBtnLogin">
                    <a href="/registrate"><div class="topBtnReg">¡Regístrate!</div></a>
                    <!-- <a href="/pais"><div class="topBtnFlag"><i class="fa fa-flag"></i></div></a> -->
                    <a href="/pais"><div class="topBtnFlag" style="background-color:transparent;"><img  data-toggle="tooltip" title="CAMBIAR PAÍS" data-placement="bottom" style="width:40px;" src="/static/images/{{request.mycountryflag}}"></div></a>
                </div>
                  <div class="topBtnLogin">
                    ¿Ya estás registrado(a)?,<br>
                    <a data-toggle="modal" href="#/logueate" data-target="#myModal">¡INICIA SESIÓN!</a>
                  </div>
                </div>
                {% endif %}
            </div>
            <div class="col-md-12 mobilePaddingBottom"></div>
        </div>


      </div>
    </div>

    <div class="container-fluid" id="fixedTopMenu">
      <div class="logoTopMenu" id="fixedTopMenuCont"></div>
      <div class="logoTopMenuContr" id="fixedTopExp"></div>
    </div>

<div class="container-fluid topMenuContainer" id="topMenuID">
  <div class="row">

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="color:black;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                 <h4 class="modal-title">Inicia sesión</h4>

            </div>
            <div class="modal-body">
              <div class="te">
                <div id="login_box">
                  <form name="login_form" id="login_form" method="post" action="/login" class="sender">
                      <div id="id_nologin"></div>
                      {%csrf_token%}
                      <div class="inputLogin">
                          <label>Nickname:</label>
                          <input type="text" name="user" value="" placeholder="nickname" /> 
                      </div>
                      <div class="inputLogin">
                          <label>Contraseña:<span>(Elige a un personaje y una figura)</span></label>
                          <input type="hidden" name="pw" id="id_password" value="" placeholder="xxx" /> 
                      </div>


                      <div class="col-md-12">
                        <div class="contrasena-selector-holder">
                            <div data-doll="barbie" class="contrasena-selector">
                              <div class="foto barbie" style="background:url('/static/barbiepass/barbie.png');"></div>
                              <div class="nombre_p changed">Barbie</div>
                            </div>
                            <div data-doll="nikki" class="contrasena-selector">
                              <div class="foto nikki" style="background:url('/static/barbiepass/niki.png');"></div>
                              <div class="nombre_p changed">Nikki</div>
                            </div>
                            <div data-doll="raquelle" class="contrasena-selector">
                              <div class="foto raquelle" style="background:url('/static/barbiepass/raquelle.png');"></div>
                              <div class="nombre_p changed">Raquelle</div>
                            </div>
                            <div data-doll="teresa" class="contrasena-selector">
                              <div class="foto teresa" style="background:url('/static/barbiepass/teresa.png');"></div>
                              <div class="nombre_p changed">Teresa</div>
                            </div>
                          </div>

                          <br/>

                          <div class="contrasena-selector-holder">
                            <div data-doll="circle" class="contrasena-selector">
                              <div class="forma changed" style="background-image:url('/static/barbiepass/circle.png');"></div>
                            </div>
                            <div data-doll="square" class="contrasena-selector">
                              <div class="forma changed" style="background-image:url('/static/barbiepass/square.png');"></div>
                            </div>
                            <div data-doll="arrow" class="contrasena-selector">
                              <div class="forma changed" style="background:url('/static/barbiepass/arrow.png');"></div>
                            </div>
                            <div data-doll="moon" class="contrasena-selector">
                              <div class="forma changed" style="background-image:url('/static/barbiepass/moon.png');"></div>
                            </div>
                          </div>
                      </div>

                      <br/><br/>


                      <input type="submit" value="login" style="display:none;" />
                  </form>
                </div>

              </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="goin">¡ENTRA!</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->




  </div>
</div>

{% if request.user.barbieuser_set.all.0 %}
{% if not request.user.barbieuser_set.all.0.enabled %}

<div class="container-fluid barRecordatorio bounceBar" id="recordatorio">
<form name="recordatorio" class="sendit" id="formrecordatorio">
     {%csrf_token%}
     <input type="hidden" name="keyus" value="{{ request.user.barbieuser_set.all.0.pk}}" />
</form>
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-2"></div>
      <div class="col-md-5">
        <p>¡HOLA {{request.user.barbieuser_set.all.0.nickname}}!</p>
        <p>Para disfrutar los beneficios y participar en nuestras promociones, pidele a tú papá que valide tu cuenta.</p>
      </div>
      <div class="col-md-3">
        <div>
          <a href="/sendrecordatorio" id="remainder"> <div class="botonRecordatorio"><i class="fa fa-envelope"></i> ¡Recordarle a mi papá!</div></a>
        </div>
      </div>
      <div class="col-md-2">
        <div class="closeRecordatorio" style="";>
          <div class=" closeInRecordatorio" id="recordatorioBtn" onclick="cerrarRecorda()" style="";><i class="fa fa-times"></i></div>
        </div>
        
      </div>

    </div>
  </div>

</div>
{% endif %}
{% endif %}

{% block last_script %}


 <script type="text/javascript" src="/static/js/passwords.js"></script>
 <script type="text/javascript">

$('#goin').click(function(){
  $('#login_form').submit();

});

countries = ['mx','pe','col','chi','latam','cr','ecu','pan'];
analisame = {'mx':'UA-65856312-4',
             'col':'UA-65856312-5',
             'chi':'UA-65856312-6',
             'pe':'UA-65856312-7',
             'latam':'UA-65856312-8'
           }

host_name = window.location.host.split('.');
if((countries.indexOf(host_name[0]))>-1)
{
  
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create',analisame[host_name[0]], 'auto');
  ga('send', 'pageview');
 function clickDownload(){
    ga('send', 'event', 'MP3', 'Descarga', 'Alcemos nuestras voces MP3 MX');
    console.log('tracking mp3');
  }
  function clickDownloadLatam(){
    ga('send', 'event', 'MP3', 'Descarga', 'Alcemos nuestras voces MP3 LATAM');
    console.log('tracking mp3');
  }
}


</script>
        <script type="text/javascript">

          $(document).ready(function(){
            $('#remainder').click(function(e){
                e.preventDefault();
                data = $('#formrecordatorio').serializeArray();
                console.log(data);
                $.ajax({url:'/mailing',data:data,type:'post',success:function(response){
                  $('#recordatorio').remove();
                }
            });
          });



          });
        </script>

          <!--  animaciones princesas  -->
         <script src="/static/vivebarbie/generales/js/animation.js"></script>
        <!-- animaciones princesas -->

{% endblock %}

mainapp/templates/parentform.html
{% extends 'base.html'%}

{% block content %}
<div id="regparent_box2">
	{% include "forms/regparent.html" %}
</div>
{% endblock %}